import { afterAll, afterEach, beforeAll, describe, expect, it } from "vitest";

import { signIn } from "@/lib/auth/session";
import { respondingRates } from "@/lib/fx/rate-stub";
import { createQuote, updateQuote } from "@/lib/quotes/quotes";
import { createServiceClient } from "@/lib/supabase/service-client";
import {
  memoryCookieStore,
  type SessionCookieStore,
} from "@/lib/supabase/session-client";
import { addAssignee, createTender, getTender } from "@/lib/tenders/tenders";

import { asPercent, parseBufferPercent, setFxBuffer } from "./fx-buffer";
import { getOrgSettings } from "./org";

/**
 * The org's FX Buffer, through the same seam the admin screen posts to and against the
 * real local Postgres.
 *
 * Two things are being held to here, and only one of them is about a form. The first is
 * that a percentage typed by a person becomes the fraction the column and every
 * `fx_rate_applied` expect — the 2 that lands as 200% is the whole reason the seam is a
 * function rather than a `Number()` in an action. The second is the promise the setting
 * makes to history: **changing it changes what the next Quote freezes and nothing that is
 * already frozen**. That one cannot be proved anywhere but here, because it is a claim
 * about two rows written on either side of an `update`, and the rows are generated by
 * the database from what was stored.
 *
 * Only the Frankfurter boundary is stubbed, as everywhere else Quotes are written.
 */

const password = "correct-horse-battery-staple";
const run = crypto.randomUUID().slice(0, 8);

const service = createServiceClient();

/** The Org Admin, who is also the Tender's Owner and an Assignee on it. */
const admin = { id: "", email: `buffer-admin-${run}@example.test` };
/** An ordinary member. The gate has to turn them away at the server, not in the menu. */
const member = { id: "", email: `buffer-member-${run}@example.test` };

let orgId = "";
let itemId = "";

/**
 * A day no other suite's rates are dated, so the `fx_rates` rows these Quotes cache can
 * be cleaned up by date without deleting a row another suite is standing on.
 */
const quotedAt = "2026-07-15";

/**
 * A currency no other suite quotes in, and the reason is not tidiness.
 *
 * `fx_rates` is reference data with no org, so it is the one table these suites genuinely
 * share while running in parallel. `quotes.test.ts` proves the `no_rate` refusal by
 * deleting **every CNY row** and then asking for a rate — so a second suite freezing CNY
 * Quotes beside it drops a cached rate into the window between that delete and that read,
 * and the refusal under test quietly succeeds instead. It fails in the other file, on a
 * test that has nothing to do with this one, and only when both happen to interleave.
 *
 * Everything here is stubbed and never reaches ECB, so the currency is free; what it must
 * be is unshared. The cleanup below deletes by `as_of` rather than by currency for the
 * same reason, pointed the other way: this suite tidies up after itself without reaching
 * into a row anybody else is using.
 */
const currency = "MYR";

async function signedInAs(email: string): Promise<SessionCookieStore> {
  const store = memoryCookieStore();
  const result = await signIn({ email, password }, store);

  if (!result.ok) throw new Error(`could not sign in as ${email}`);

  return store;
}

async function createMember(
  who: { id: string; email: string },
  { isOrgAdmin = false }: { isOrgAdmin?: boolean } = {},
) {
  const { data, error } = await service.auth.admin.createUser({
    email: who.email,
    password,
    email_confirm: true,
  });

  if (error) throw error;

  who.id = data.user.id;

  const { error: profileError } = await service.from("users").insert({
    id: who.id,
    org_id: orgId,
    name: who.email,
    email: who.email,
    is_org_admin: isOrgAdmin,
  });

  if (profileError) throw profileError;
}

/** What the column really holds, read past `getOrgSettings` and its fallback. */
async function storedBuffer(): Promise<number | null> {
  const { data } = await service
    .from("orgs")
    .select("fx_buffer_pct")
    .eq("id", orgId)
    .maybeSingle();

  return data === null ? null : Number(data.fx_buffer_pct);
}

/** The rate pair one Quote froze, as the database generated it. */
async function frozenRateOf(quoteId: string) {
  const { data, error } = await service
    .from("quotes")
    .select("fx_rate_mid, fx_rate_applied, fx_rate_as_of")
    .eq("id", quoteId)
    .single();

  if (error) throw error;

  return {
    mid: Number(data.fx_rate_mid),
    applied: Number(data.fx_rate_applied),
    asOf: data.fx_rate_as_of,
  };
}

/** A Quote in a foreign currency, which is the case that has a rate to buffer at all. */
async function aQuoteAt(rate: number, store: SessionCookieStore): Promise<string> {
  const result = await createQuote(
    {
      tenderItemId: itemId,
      supplierName: `Ace Medical ${crypto.randomUUID().slice(0, 8)}`,
      unitPrice: 100,
      currency,
      quotedUnit: "box of 50",
      leadTimeDays: 14,
      matchType: "exact",
      alternativeProductName: null,
      detailNotes: null,
      quotedAt,
    },
    store,
    respondingRates(rate),
  );

  if (!result.ok) throw new Error(`could not create a Quote: ${result.reason}`);

  return result.quoteId;
}

beforeAll(async () => {
  const { data, error } = await service
    .from("orgs")
    .insert({ name: `Buffer ${run}` })
    .select("id")
    .single();

  if (error) throw error;

  orgId = data.id;

  await createMember(admin, { isOrgAdmin: true });
  await createMember(member);

  const store = await signedInAs(admin.email);
  const tender = await createTender(
    {
      clientName: "Bangkok General Hospital",
      title: "Surgical consumables Q3",
      dateReceived: "2026-07-01",
      internalQuoteDeadline: "2026-07-20",
      clientSubmissionDeadline: "2026-07-28",
      expectedDecisionDate: null,
      ownerUserId: admin.id,
      notes: null,
      items: [
        {
          productName: "Nitrile gloves, powder-free",
          description: null,
          quantity: 500,
          unit: "box of 50",
        },
      ],
    },
    store,
  );

  if (!tender.ok) throw new Error(`could not create a Tender: ${tender.reason}`);

  const added = await addAssignee({ tenderId: tender.tenderId, userId: admin.id }, store);

  if (!added.ok) throw new Error(`could not assign the admin: ${added.reason}`);

  itemId = (await getTender(tender.tenderId, store))!.items[0].id;
});

afterEach(async () => {
  await service.from("quotes").delete().eq("tender_item_id", itemId);
  await service.from("suppliers").delete().eq("org_id", orgId);
  await service.from("fx_rates").delete().eq("as_of", quotedAt);
  // The documented default, back where every other test in this file starts.
  await service.from("orgs").update({ fx_buffer_pct: 0.02 }).eq("id", orgId);
});

afterAll(async () => {
  await service.from("tenders").delete().eq("org_id", orgId);
  await service.from("suppliers").delete().eq("org_id", orgId);

  const memberIds = [admin.id, member.id].filter(Boolean);

  await service.from("users").delete().in("id", memberIds);

  for (const id of memberIds) {
    await service.auth.admin.deleteUser(id);
  }

  await service.from("orgs").delete().eq("id", orgId);
});

describe("reading a percentage a person typed", () => {
  it("turns a whole number of percent into the fraction the column holds", () => {
    // The failure this whole seam exists for: a 2 that lands as 2 rather than as 0.02
    // multiplies every foreign price by three.
    expect(parseBufferPercent("2")).toEqual({ ok: true, fraction: 0.02 });
  });

  it("keeps the two decimal places the column has room for", () => {
    expect(parseBufferPercent("2.25")).toEqual({ ok: true, fraction: 0.0225 });
    expect(parseBufferPercent("1.1")).toEqual({ ok: true, fraction: 0.011 });
    // Trailing zeros are not precision. Refusing this would be refusing 2.5%.
    expect(parseBufferPercent("2.500")).toEqual({ ok: true, fraction: 0.025 });
  });

  it("allows no buffer at all, which is a decision rather than an error", () => {
    expect(parseBufferPercent("0")).toEqual({ ok: true, fraction: 0 });
  });

  it("forgives the percent sign the label is already showing", () => {
    // Including the full-width forms a Chinese IME produces, which look identical on the
    // screen to the reader who typed them and parse as nothing at all.
    expect(parseBufferPercent(" 2.5% ")).toEqual({ ok: true, fraction: 0.025 });
    expect(parseBufferPercent("２.５％")).toEqual({ ok: true, fraction: 0.025 });
  });

  it("refuses what is not a number, rather than reading it as zero", () => {
    // `Number("")` is 0, and a zero buffer is the direction that loses money silently.
    for (const entered of ["", "   ", "two", "2.5.1", "1e3", "2 5"]) {
      expect(parseBufferPercent(entered)).toEqual({
        ok: false,
        reason: "not_a_percentage",
      });
    }
  });

  it("refuses a negative buffer, which would convert at better than the market", () => {
    expect(parseBufferPercent("-1")).toEqual({ ok: false, reason: "out_of_range" });
  });

  it("refuses a figure past the ceiling — the 2 that was meant to be 2%", () => {
    expect(parseBufferPercent("200")).toEqual({ ok: false, reason: "out_of_range" });
    expect(parseBufferPercent("10.01")).toEqual({ ok: false, reason: "out_of_range" });
    // The ceiling itself is allowed: it is a bound on typos, not on the business.
    expect(parseBufferPercent("10")).toEqual({ ok: true, fraction: 0.1 });
  });

  it("refuses more precision than the column keeps, rather than rounding it away", () => {
    // `numeric(5,4)` would take 0.00125 and silently store 0.0013 — a different setting
    // from the one somebody typed, reported as saved.
    expect(parseBufferPercent("0.125")).toEqual({ ok: false, reason: "too_precise" });
  });

  it("shows back what it stored, as the percentage it was entered as", () => {
    // The round trip the form depends on: the box is filled from the column.
    expect(asPercent(0.02)).toBe(2);
    expect(asPercent(0.0225)).toBe(2.25);
    expect(asPercent(0)).toBe(0);
  });
});

describe("setting the buffer", () => {
  it("stores the fraction, and the app reads the new one back", async () => {
    const store = await signedInAs(admin.email);

    const result = await setFxBuffer({ entered: "3.5" }, store);

    expect(result).toEqual({ ok: true });
    // What was stored is read off the column rather than out of the return value: the
    // conversion is the thing under test, and a result that reported its own arithmetic
    // back would be agreeing with itself.
    expect(await storedBuffer()).toBeCloseTo(0.035, 8);
    expect((await getOrgSettings(store)).fxBufferPct).toBeCloseTo(0.035, 8);
  });

  it("refuses a member who is not an Org Admin, at the server", async () => {
    // The menu does not draw them the screen, but a server action is a public endpoint
    // and this is the one column that re-prices every future Quote in the org.
    const store = await signedInAs(member.email);

    expect(await setFxBuffer({ entered: "5" }, store)).toEqual({
      ok: false,
      reason: "not_admin",
    });
    expect(await storedBuffer()).toBeCloseTo(0.02, 8);
  });

  it("leaves the stored value alone when it refuses one", async () => {
    const store = await signedInAs(admin.email);

    for (const entered of ["", "200", "-1", "0.125"]) {
      expect(await setFxBuffer({ entered }, store)).toMatchObject({ ok: false });
    }

    expect(await storedBuffer()).toBeCloseTo(0.02, 8);
  });
});

describe("what changing it does to Quotes", () => {
  it("re-prices the next Quote and leaves the ones already frozen alone", async () => {
    const store = await signedInAs(admin.email);

    const before = await aQuoteAt(5, store);

    expect(await frozenRateOf(before)).toMatchObject({ mid: 5, applied: 5.1 });

    const changed = await setFxBuffer({ entered: "3.5" }, store);

    expect(changed.ok).toBe(true);

    const after = await aQuoteAt(5, store);

    // The next Quote freezes the new buffer …
    expect((await frozenRateOf(after)).applied).toBeCloseTo(5 * 1.035, 8);
    // … and the one entered a moment earlier still holds the pair it was entered with.
    // A change that reached back through history would be the bug, not the feature.
    expect(await frozenRateOf(before)).toMatchObject({
      mid: 5,
      applied: 5.1,
      asOf: quotedAt,
    });
  });

  it("leaves an existing Quote alone when it is corrected without moving its date", async () => {
    // The correction path is the only thing in the app that can rewrite an already-frozen
    // pair, so "nothing already frozen moves" is not proved by the create path alone
    // (ADR-0016: the case has to be produced). A price correction is not a claim about a
    // currency, so all four rate fields stay exactly where they were — across a buffer
    // change that would otherwise have re-priced them.
    const store = await signedInAs(admin.email);

    const quoteId = await aQuoteAt(5, store);

    expect(await setFxBuffer({ entered: "3.5" }, store)).toMatchObject({ ok: true });

    const corrected = await updateQuote(
      {
        quoteId,
        supplierName: "Ace Medical",
        unitPrice: 130,
        quotedUnit: "box of 50",
        leadTimeDays: 14,
        matchType: "exact",
        alternativeProductName: null,
        detailNotes: null,
        quotedAt,
      },
      store,
      respondingRates(9.99),
    );

    expect(corrected.ok).toBe(true);
    expect(await frozenRateOf(quoteId)).toMatchObject({
      mid: 5,
      applied: 5.1,
      asOf: quotedAt,
    });
  });

  it("re-freezes at the buffer that stands now when the day a Quote claims is corrected", async () => {
    // The one already-frozen pair that moves, and it moves for ADR-0018's reason rather
    // than this setting's: the Quote now claims a different day, so it gets that day's
    // rate — and it gets it the way the create path would, at the buffer as it stands.
    // Reconstructing the retired buffer from `applied / mid - 1` would produce a row the
    // create path could not, which is the invariant ADR-0018 exists to hold.
    //
    // Written down as a test rather than left implied, because it is the sentence the
    // screen makes to an Org Admin: a Quote already recorded keeps its rate *unless
    // somebody corrects the day it claims*. Without this, that exception is a claim
    // nothing checks.
    const store = await signedInAs(admin.email);

    const quoteId = await aQuoteAt(5, store);

    expect(await setFxBuffer({ entered: "3.5" }, store)).toMatchObject({ ok: true });

    const movedTo = "2026-07-16";
    const corrected = await updateQuote(
      {
        quoteId,
        supplierName: "Ace Medical",
        unitPrice: 100,
        quotedUnit: "box of 50",
        leadTimeDays: 14,
        matchType: "exact",
        alternativeProductName: null,
        detailNotes: null,
        quotedAt: movedTo,
      },
      store,
      respondingRates(8),
    );

    expect(corrected.ok).toBe(true);

    const rate = await frozenRateOf(quoteId);

    expect(rate.mid).toBeCloseTo(8, 8);
    expect(rate.applied).toBeCloseTo(8 * 1.035, 8);
    expect(rate.asOf).toBe(movedTo);

    await service.from("fx_rates").delete().eq("as_of", movedTo);
  });
});
