#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — the three hand-checks left open on #48.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=8

# ── Author-level helpers (verdict capture) ────────────────────────────────
# This wizard's product is a set of verdicts, not credentials. Every verdict is
# appended to $FINDINGS the moment it is given, so Ctrl-C mid-run never loses a
# check you already ran on the phone. Nothing captured here is a secret, and
# nothing secret is ever written to it: the Group Robot webhook is a bearer
# credential, so it is read into a shell variable for one curl and never
# persisted, never echoed, and never recorded.

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
# Assigned unconditionally, and this is the whole reason why: the library above
# already did `ENV_FILE="${ENV_FILE:-.env}"`, so a `${ENV_FILE:-…}` here would
# quietly keep `.env` — which on this repo holds four WeCom keys and no Supabase
# ones. The seeder would then be handed a file that exists and says nothing, and
# would fail three stages later with "must both be set". Override with
# PROD_ENV_FILE, not ENV_FILE.
ENV_FILE="${PROD_ENV_FILE:-$REPO_ROOT/.env.production}"
FINDINGS="${FINDINGS:-$REPO_ROOT/.wizard/48-phone-checks.md}"

mkdir -p "$(dirname "$FINDINGS")"

# record "text" — append a line to the findings file.
record() { printf '%s\n' "$1" >> "$FINDINGS"; }

# record_verdict "Check" "verdict" "notes" — one findings block per check.
record_verdict() {
  record ""
  record "### $1"
  record ""
  record "**Verdict: $2**"
  record ""
  record "${3:-_(no notes)_}"
}

# ask_note KEY "Prompt" — single-line answer. Unlike ask(), never consults
# .env: a verdict is not a credential and must not be defaulted from one.
ask_note() {
  local key="$1" prompt="$2" input
  printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  read -r input || true
  printf -v "$key" '%s' "$input"
}

# ask_block KEY "Prompt" — multi-line capture, terminated by a lone dot.
ask_block() {
  local key="$1" prompt="$2" line acc=""
  printf '  %s%s%s\n' "$BOLD" "$prompt" "$RESET"
  note "  paste as many lines as you like, then a single . on its own line"
  while IFS= read -r line; do
    [[ "$line" == "." ]] && break
    acc="$acc$line
"
  done
  printf -v "$key" '%s' "${acc%$'\n'}"
}

# ask_choice KEY "Prompt" opt1 opt2 … — pick one; KEY gets the option text.
ask_choice() {
  local key="$1" prompt="$2"; shift 2
  local input i opt
  printf '  %s%s%s\n' "$BOLD" "$prompt" "$RESET"
  i=1; for opt in "$@"; do printf '    %s%s)%s %s\n' "$BLUE" "$i" "$RESET" "$opt"; i=$((i + 1)); done
  while :; do
    printf '  %sChoose 1-%s:%s ' "$BOLD" "$#" "$RESET"
    read -r input || true
    if [[ "$input" =~ ^[0-9]+$ ]] && [ "$input" -ge 1 ] && [ "$input" -le "$#" ]; then
      eval "printf -v \"\$key\" '%s' \"\${$input}\""
      return 0
    fi
    warn "pick a number between 1 and $#"
  done
}

# env_value KEY — read a value out of $ENV_FILE without sourcing it.
env_value() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  line="${line#*=}"
  line="${line%\"}"; line="${line#\"}"
  printf '%s' "$line"
}

banner "#48 — the three phone checks that gate launch"

# ──────────────────────────────────────────────────────────────────────────
stage "Preflight — is the deployment even checkable?"
say "Two of these checks depend on reminders carrying a link, which is the whole"
say "of #59. If APP_ORIGIN is not configured in production, every link comes back"
say "null and check 2 is un-runnable again — exactly the way it was last time."
printf '\n'

# Four keys carry this whole run: two the seeder writes past RLS with, one the
# links are built from, one the cron is authorised by. Test for the keys rather
# than for the file — a file that exists is not the same as a file that answers.
REQUIRED_KEYS=(NEXT_PUBLIC_SUPABASE_URL SUPABASE_SERVICE_ROLE_KEY APP_ORIGIN CRON_SECRET)

missing_keys() {
  local key out=""
  for key in "${REQUIRED_KEYS[@]}"; do
    [[ -n "$(env_value "$key" || true)" ]] || out="$out $key"
  done
  printf '%s' "${out# }"
}

MISSING="$(missing_keys)"

if [[ -n "$MISSING" ]]; then
  note "Not yet in $ENV_FILE: $MISSING"
  step "Pulling the production environment (you may be asked to log in)."
  vercel env pull "$ENV_FILE" --environment=production || \
    warn "vercel env pull failed"
  MISSING="$(missing_keys)"
fi

if [[ -n "$MISSING" ]]; then
  printf '\n'
  warn "still missing from $ENV_FILE: $MISSING"
  warn "Every one of them is set on Vercel Production, so the pull is the fix:"
  note "  vercel env pull $ENV_FILE --environment=production"
  printf '\n'
  warn "Stopping here rather than three stages in, where the seeder would fail"
  warn "with 'must both be set' and the reason would be this."
  exit 1
fi

APP_URL="$(env_value APP_ORIGIN)"
APP_URL="${APP_URL%/}"
note "Origin: $APP_URL"

step "Asking the deployment what it thinks of its own configuration."
HEALTH="$(curl -sS --max-time 20 "$APP_URL/api/health" || echo '{"status":"unreachable"}')"
printf '\n  %s\n\n' "$HEALTH"

if printf '%s' "$HEALTH" | grep -qi "origin"; then
  warn "/api/health is saying something about the origin. Read it above."
  warn "If APP_ORIGIN is missing or wrong, STOP: fix it and redeploy first."
  confirm "APP_ORIGIN is good and you want to carry on anyway?" || {
    say "Stopping here. Nothing has been changed."; exit 0; }
fi

record "# #48 — phone checks, run $(date +%Y-%m-%d)"
record ""
record "Run with \`.scratch/tender-tracker-mvp/wizard-48-phone-checks.sh\` against $APP_URL."
record "Re-run of the three boxes left unticked on 2026-08-27, after #56 (390px) and #59 (reminder links) shipped."
ask_note DEVICES "Device and WeCom version (e.g. iPhone 14 Pro Max · WeCom 5.0.10):"
record ""
record "**Devices:** ${DEVICES:-_(not recorded)_}"
pause "Preflight done. Enter to continue."

# ──────────────────────────────────────────────────────────────────────────
stage "Seed the Tender the photo flow hangs off"
say "The photo controls hang off a *saved Quote row*, so an empty deployment has"
say "nowhere to add a photo at all. This seeds one throwaway Tender → Item → Quote."
printf '\n'
note "Deadlines go 80 and 110 days out, so this one nudges nobody."
printf '\n'

if confirm "Seed the mock Tender in production now?"; then
  SEED_OUT="$(node --env-file="$ENV_FILE" "$REPO_ROOT/scripts/seed-mock-tender.mjs" 2>&1)" || \
    warn "the seeder failed — read the output below"
  printf '%s\n' "$SEED_OUT"
  SOURCING_URL="$(printf '%s' "$SEED_OUT" | grep -oE 'https?://[^ ]+/quote' | head -n1)"
else
  SKIPPED+=("seeding the mock Tender")
fi

[[ -n "${SOURCING_URL:-}" ]] || ask_note SOURCING_URL "Paste the sourcing screen URL (…/items/…/quote):"
pause "Enter when you have that URL open on your phone."

# ──────────────────────────────────────────────────────────────────────────
stage "Check 1 — 390px density, on the phone"
say "#56 added headless coverage at 390×844. This is the half a green test cannot"
say "give you: whether the density is *usable* and the tap targets are honestly 44px."
printf '\n'
step "Walk these on the phone, in this order:"
note "  1. the tender list          $APP_URL/tenders"
note "  2. a tender                 tap the mock one from that list"
note "  3. sourcing an item         $SOURCING_URL"
note "  4. correcting a quote       tap Edit on the saved Quote row"
note "  5. the same sourcing screen after picking two photos (the held-photo list)"
printf '\n'
warn "Judge it. A passing measurement on a cramped screen is not the answer."
printf '\n'
ask_choice DENSITY "Density and tap targets, across all five:" \
  "pass — usable, and nothing is under a thumb" \
  "fail — still too cramped, or something is untappable" \
  "partial — most held, some screen did not"
ask_block DENSITY_NOTES "Which screens, and what was wrong? (a lone . to finish)"
record_verdict "1. 390px density and 44px tap targets, after #56" "$DENSITY" "$DENSITY_NOTES"
pause "Recorded. Enter to continue."

# ──────────────────────────────────────────────────────────────────────────
stage "Check 3 — does WeCom autolink a bare URL?"
say "Run before the reminder check on purpose: if WeCom does not autolink a bare"
say "URL, the reminder check's first clause cannot pass either, and you have"
say "learned it for the price of one message instead of a whole cron run."
printf '\n'
warn "This posts a real message into the company group."
printf '\n'
note "The webhook is a bearer credential. It is read for one curl and never stored."
ask_secret ROBOT_WEBHOOK "Paste the Group Robot webhook URL:"

if [[ -n "$ROBOT_WEBHOOK" ]] && confirm "Post the test message to the group now?"; then
  # A bare URL alone on its last line, with no punctuation after it — the exact
  # shape linkLine() builds in src/lib/wecom/messages.ts. Anything else tests a
  # message this app does not send.
  PAYLOAD=$(printf '{"msgtype":"text","content":{"content":"%s\\n%s"}}' \
    "Ignore — testing whether a link is tappable." "$APP_URL/tenders")
  RESP="$(curl -sS --max-time 20 -H 'Content-Type: application/json' \
    -d "$PAYLOAD" "$ROBOT_WEBHOOK" || echo '{"errcode":"curl failed"}')"
  printf '\n  %s\n\n' "$RESP"
  printf '%s' "$RESP" | grep -q '"errcode":0' || warn "that does not look like errcode 0 — read it above"
else
  SKIPPED+=("posting the bare-URL test message")
fi

step "On the phone, open the group and look at that message."
ask_choice AUTOLINK "Is the bare URL rendered as a tappable link?" \
  "pass — tappable, and it opens the app" \
  "fail — plain text, not tappable" \
  "partial — tappable but it left WeCom / opened the wrong place"
ask_block AUTOLINK_NOTES "What did it look like, and where did it open? (a lone . to finish)"
record_verdict "3. A bare URL in a group-robot text message is tappable" "$AUTOLINK" "$AUTOLINK_NOTES"

if [[ "$AUTOLINK" == fail* ]]; then
  printf '\n'
  warn "A 'no' here is an ADR-0012 amendment, not a bug fix: the fallback is the"
  warn "markdown message type, which ADR-0012 forbids outright. Do not work around"
  warn "it — take it to a decision. Check 2 below cannot pass as written either."
  pause "Enter to carry on and record the rest anyway."
fi

# ──────────────────────────────────────────────────────────────────────────
stage "Arm a genuine reminder, and fire the cron"
say "Check 2 reads 'a reminder link opens the app'. On 2026-08-27 that was measured"
say "against a link hand-posted into the group, because reminders carried none."
say "#59 fixed that, so this time it gets run as written — from a real reminder."
printf '\n'
note "--due-soon puts the internal deadline exactly three days out, which lands one"
note "reminder on today and leaves the rest of the ramp in the future."
printf '\n'
warn "This posts a real reminder into the company group, naming the mock Tender."
printf '\n'

if confirm "Seed the due-soon Tender and fire the cron?"; then
  node --env-file="$ENV_FILE" "$REPO_ROOT/scripts/seed-mock-tender.mjs" --due-soon || \
    warn "the seeder failed — read the output above"

  # Guaranteed by the preflight, which refuses to start without it.
  CRON_SECRET_VALUE="$(env_value CRON_SECRET)"

  step "Calling the daily cron."
  CRON_RESP="$(curl -sS --max-time 60 -H "Authorization: Bearer $CRON_SECRET_VALUE" \
    "$APP_URL/api/cron/daily" || echo '{"status":"curl failed"}')"
  printf '\n  %s\n\n' "$CRON_RESP"
  printf '%s' "$CRON_RESP" | grep -q '"status":"ok"' || \
    warn "not an ok — a 404 here means CRON_SECRET is wrong or unset in production"
  note "Reminders are marked sent once posted. For a second attempt, --undo and re-seed."
else
  SKIPPED+=("firing a genuine reminder (check 2 stays un-runnable as written)")
fi
pause "Enter when the reminder is in the group."

# ──────────────────────────────────────────────────────────────────────────
stage "Check 2 — the WeCom in-app webview, as written"
say "All four clauses, on the phone, starting from the reminder in the group."
printf '\n'
step "1. Tap the link in the reminder. Does it open the app in the webview?"
step "2. Log in. Any security banner? Any 'open in your browser' advice?"
step "3. On the sourcing screen, tap the photo input. Does the camera open?"
step "4. Take a photo. Does compress-and-upload complete?"
printf '\n'
note "Login and the photo input have both changed since this was last measured."
note "That is the whole reason it is on the list — do not skim it."
printf '\n'
ask_choice WEBVIEW_LINK   "Clause 1 — the reminder link opens the app:" "pass" "fail" "not run"
ask_choice WEBVIEW_LOGIN  "Clause 2 — login, no banner, no 'open in browser':" "pass" "fail" "not run"
ask_choice WEBVIEW_CAMERA "Clause 3 — the camera opens from the photo input:" "pass" "fail" "not run"
ask_choice WEBVIEW_UPLOAD "Clause 4 — compress-and-upload completes:" "pass" "fail" "not run"
ask_block WEBVIEW_NOTES "Anything else worth writing down? (a lone . to finish)"

if [[ "$WEBVIEW_LINK" == pass && "$WEBVIEW_LOGIN" == pass && \
      "$WEBVIEW_CAMERA" == pass && "$WEBVIEW_UPLOAD" == pass ]]; then
  WEBVIEW="pass — all four clauses, from a genuine reminder"
else
  WEBVIEW="not a clean pass — see the clauses below"
fi

record_verdict "2. The WeCom in-app webview, run as written" "$WEBVIEW" \
"| Clause | Verdict |
| --- | --- |
| The reminder link opens the app | $WEBVIEW_LINK |
| Login: no security banner, no 'open in your browser' | $WEBVIEW_LOGIN |
| The camera opens from the photo input | $WEBVIEW_CAMERA |
| Compress-and-upload completes | $WEBVIEW_UPLOAD |

${WEBVIEW_NOTES:-_(no further notes)_}"
pause "Recorded. Enter to continue."

# ──────────────────────────────────────────────────────────────────────────
stage "Take the mock data back out"
say "Both seeded Tenders share one title, so one --undo removes them together."
printf '\n'
warn "This deletes from production. It deletes only rows titled"
warn "'MOCK — phone check (safe to delete)' and what cascades from them."
printf '\n'

if confirm "Run the undo now?"; then
  node --env-file="$ENV_FILE" "$REPO_ROOT/scripts/seed-mock-tender.mjs" --undo || \
    warn "the undo failed — the mock rows are still there, remove them by hand"
else
  SKIPPED+=("removing the mock Tenders (run the seeder with --undo)")
fi

note "The group still has a mock reminder and a test link in it. Worth one line"
note "in the group saying it was a test, so nobody chases a Tender that is gone."
pause "Enter to continue."

# ──────────────────────────────────────────────────────────────────────────
stage "Put the verdicts on #48"
say "The findings are written to:"
note "  $FINDINGS"
printf '\n'
say "That file is gitignored. #48 is where the launch gate is read, so the"
say "verdicts belong on the ticket rather than only on this machine."
printf '\n'

if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  if confirm "Post these verdicts as a comment on #48?"; then
    gh issue comment 48 --body-file "$FINDINGS" && \
      printf '  %s✓ posted%s to #48\n' "$GREEN" "$RESET"
  else
    SKIPPED+=("posting to #48 (gh issue comment 48 --body-file $FINDINGS)")
  fi
else
  SKIPPED+=("posting to #48 — gh not ready (gh issue comment 48 --body-file $FINDINGS)")
fi

printf '\n'
say "Tick the boxes on #48 yourself, against these verdicts — and only the ones"
say "that actually passed. That ticket exists to refuse a green tick nobody earned."
printf '\n'
note "A fail on the bare-URL check is an ADR-0012 decision, not a bug to file."

finish
