#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10

# ── Author-level helpers (findings capture) ───────────────────────────────
# This wizard's main product is a findings document, not credentials. Every
# observation is appended to $FINDINGS as it is made, so Ctrl-C mid-run never
# loses what you already saw. Secrets go to $ENV_FILE only — the ticket is
# explicit that no credential may be pasted into any ticket or findings file.

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="${ENV_FILE:-$REPO_ROOT/.env}"
FINDINGS="${FINDINGS:-$REPO_ROOT/.scratch/tender-tracker-mvp/research/06-wecom-console.md}"
SHOTS_DIR="$REPO_ROOT/.scratch/tender-tracker-mvp/research"

WEBHOOK_BASE="https://qyapi.weixin.qq.com/cgi-bin/webhook/send"
QYAPI="https://qyapi.weixin.qq.com/cgi-bin"

# record "text" — append a line to the findings file.
record() { printf '%s\n' "$1" >> "$FINDINGS"; }

# record_kv "Label" "value" — a findings bullet, with a placeholder when blank.
record_kv() { record "- **$1:** ${2:-_(not recorded)_}"; }

# record_label "Label:" — a label line, blank-separated so it never gets
# swallowed into the preceding bullet list as a lazy continuation.
record_label() { record ""; record "$1"; }

# record_fenced "lang" "text" — append a fenced block, trimming the trailing
# newline ask_block accumulates so the fence has no stray blank last line.
record_fenced() { record '```'"$1"; printf '%s\n' "${2%$'\n'}" >> "$FINDINGS"; record '```'; record ""; }

# ask_note KEY "Prompt" — single-line answer. Unlike ask(), never consults
# .env: findings are not credentials and must not be defaulted from one.
ask_note() {
  local key="$1" prompt="$2" input
  printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  read -r input || true
  printf -v "$key" '%s' "$input"
}

# ask_block KEY "Prompt" — multi-line verbatim capture, for transcribing
# console text exactly as the ticket demands. Terminated by a lone dot.
ask_block() {
  local key="$1" prompt="$2" line acc=""
  printf '  %s%s%s\n' "$BOLD" "$prompt" "$RESET"
  note "  paste as many lines as you like, then a single . on its own line"
  while IFS= read -r line; do
    [[ "$line" == "." ]] && break
    acc="$acc$line
"
  done
  printf -v "$key" '%s' "$acc"
}

# ask_choice KEY "Prompt" opt1 opt2 … — pick one; KEY gets the option text.
ask_choice() {
  local key="$1" prompt="$2"; shift 2
  local input i opt
  printf '  %s%s%s\n' "$BOLD" "$prompt" "$RESET"
  i=1; for opt in "$@"; do printf '    %s%s)%s %s\n' "$BLUE" "$i" "$RESET" "$opt"; i=$((i + 1)); done
  while :; do
    printf '  %sChoose 1-%s:%s ' "$BOLD" "$#" "$RESET"
    read -r input || true
    if [[ "$input" =~ ^[0-9]+$ ]] && [ "$input" -ge 1 ] && [ "$input" -le "$#" ]; then
      eval "printf -v \"\$key\" '%s' \"\${$input}\""
      return 0
    fi
    warn "enter a number between 1 and $#"
  done
}

# robot_send JSON — POST to the group robot. Never echoes the webhook URL
# (the key in it is the credential). Prints and returns the response body.
robot_send() {
  curl -sS -X POST -H 'Content-Type: application/json' \
    -d "$1" "$WEBHOOK_BASE?key=$ROBOT_KEY" 2>&1 || true
}

# ── Preflight ─────────────────────────────────────────────────────────────
# Refuse to run without a terminal. Every prompt would read EOF, and the two
# validating loops (webhook URL, ask_choice) would spin forever on the empty
# value they can never accept. Run this from your own shell, not an agent.
if [[ ! -t 0 ]]; then
  printf 'This wizard is interactive — run it from a terminal, not a pipe.\n' >&2
  exit 1
fi
for _bin in curl jq; do
  command -v "$_bin" >/dev/null 2>&1 || { printf 'This wizard needs %s on PATH.\n' "$_bin" >&2; exit 1; }
done
mkdir -p "$(dirname "$FINDINGS")"
if [[ ! -f "$FINDINGS" ]]; then
  record "# 06 — WeCom console: observed facts"
  record ""
  record "Console findings for ticket \`issues/06-register-wecom-app-and-robot.md\`."
  record "Written by \`wizard-06-wecom.sh\`. **No credentials in this file** — those live in"
  record "\`.env\` at the repo root (gitignored). Tickets 07 and 12 read this."
  record ""
fi
record "---"
record ""
record "## Session $(date '+%Y-%m-%d %H:%M %Z')"
record ""

banner "WeCom console — ticket 06"

# ── Stage 1 — the group robot ─────────────────────────────────────────────
stage "Group robot — create it and capture the webhook"
say "Ticket 06's most load-bearing claim is the group robot. It needs no trusted"
say "domain, no ICP filing and no IP whitelist, so this stage should succeed even"
say "if every later stage hits a wall. We do it first for exactly that reason."
printf '\n'
warn "Use a THROWAWAY test group, not the real team group — stage 5 bursts ~25 messages."
step "Open the WeCom desktop or mobile client (NOT the admin console — group"
step "  robots are created from the chat, not from work.weixin.qq.com)."
step "Create a group: include yourself and, if you can, one colleague."
step "In the group: ⋯ / 群设置 → 群机器人 (Group Robots) → 添加机器人 (Add)."
step "Name it something like 'tender-tracker-test', then copy its Webhook URL."
note "Reference: https://developer.work.weixin.qq.com/document/path/91770"
open_url "https://developer.work.weixin.qq.com/document/path/91770"
printf '\n'
while :; do
  ask_secret WECOM_ROBOT_WEBHOOK "Paste the robot Webhook URL (hidden):"
  case "$WECOM_ROBOT_WEBHOOK" in
    "$WEBHOOK_BASE?key="*) break ;;
    *) warn "that doesn't look right — it should start ${WEBHOOK_BASE}?key=" ;;
  esac
done
ROBOT_KEY="${WECOM_ROBOT_WEBHOOK#*key=}"
write_env WECOM_ROBOT_WEBHOOK "$WECOM_ROBOT_WEBHOOK"
ask_note GROUP_DESC "How many people are in this group (including you)?"
record "### 1. Group robot"
record_kv "Robot created" "yes"
record_kv "Group size" "$GROUP_DESC"
record_kv "Webhook stored in" "\`.env\` → \`WECOM_ROBOT_WEBHOOK\` (repo root, gitignored)"
record ""
pause "Robot created. Press Enter to test the mention."

# ── Stage 2 — the @mention that carries the product ───────────────────────
stage "Mention test A — @mention yourself"
say "Ticket 08's entire notification design rests on mentioned_mobile_list."
say "It has never been tested against a real group. This is that test."
printf '\n'
warn "USE E.164 WITH A LEADING + — e.g. +66933555055. Established 2026-08-12:"
warn "that format notifies; '66…', '0…' and the bare national number are all"
warn "silently ACCEPTED (errcode 0), delivered, and never bind the mention."
warn "'@all' does not notify either. There is no error for a wrong format."
printf '\n'
ask_note MY_MOBILE "Your mobile number (digits only):"
PAYLOAD_A=$(jq -nc --arg m "$MY_MOBILE" \
  '{msgtype:"text",text:{content:"[06] mention test A — this should notify you.",mentioned_mobile_list:[$m]}}')
say "Sending…"
RESP_A=$(robot_send "$PAYLOAD_A")
printf '\n'; say "Response: $RESP_A"; printf '\n'
warn "Now LOOK AT YOUR PHONE. The question is not whether the text says '@you'."
warn "It is whether WeCom gave you an actual mention notification."
ask_choice MENTION_A "What actually happened?" \
  "Real @mention — highlighted, and I got a notification" \
  "Message arrived, but the mention is plain text with no notification" \
  "Message arrived with no mention rendering at all" \
  "Nothing arrived / the call errored"
record "### 2. Mention test A — self"
record_kv "Number format used" "\`$MY_MOBILE\`"
record_kv "Observed result" "$MENTION_A"
record_label "Payload that was sent:"
record_fenced json "$PAYLOAD_A"
record_label "Response:"
record_fenced json "$RESP_A"
case "$MENTION_A" in
  "Real @mention"*) say "Good — ticket 08's design holds." ;;
  *) warn "Retry with a different number format before concluding. If no format"
     warn "produces a real mention, ticket 08 must be REOPENED: targeted reminders,"
     warn "the nag rule and per-Assignee notifications all collapse to broadcast." ;;
esac
pause "Press Enter to continue."

# ── Stage 3 — a number that is not in the group ───────────────────────────
stage "Mention test B — a number NOT in the group"
say "The notification code will sometimes mention someone who has left the group."
say "If that errors rather than being ignored, the design needs a guard."
printf '\n'
note "Default is an unassigned-looking number so no real person gets pinged."
ask_note OTHER_MOBILE "Number NOT in the group [Enter for 13800000000]:"
[[ -z "$OTHER_MOBILE" ]] && OTHER_MOBILE="13800000000"
PAYLOAD_B=$(jq -nc --arg m "$OTHER_MOBILE" \
  '{msgtype:"text",text:{content:"[06] mention test B — non-member number.",mentioned_mobile_list:[$m]}}')
RESP_B=$(robot_send "$PAYLOAD_B")
printf '\n'; say "Response: $RESP_B"; printf '\n'
ask_choice MENTION_B "What happened?" \
  "Message delivered, unknown number silently ignored (expected)" \
  "Message delivered but errcode was non-zero" \
  "Message rejected outright" \
  "Something else"
record "### 3. Mention test B — non-member number"
record_kv "Number tried" "\`$OTHER_MOBILE\`"
record_kv "Observed result" "$MENTION_B"
record_label "Response:"
record_fenced json "$RESP_B"
[[ "$MENTION_B" == "Message delivered, unknown"* ]] || \
  warn "Not the expected behaviour — ticket 08's notification code needs a guard."
pause "Press Enter to continue."

# ── Stage 4 — does it render for someone else ─────────────────────────────
stage "Mention test C — a second person"
say "A mention that only works for the sender is not a notification system."
printf '\n'
if confirm "Is a colleague in the group and able to check their phone now?"; then
  ask_note THEIR_MOBILE "Their mobile number (digits only):"
  PAYLOAD_C=$(jq -nc --arg m "$THEIR_MOBILE" \
    '{msgtype:"text",text:{content:"[06] mention test C — please confirm you were notified.",mentioned_mobile_list:[$m]}}')
  RESP_C=$(robot_send "$PAYLOAD_C")
  printf '\n'; say "Response: $RESP_C"; printf '\n'
  step "Ask them: did you get a real notification, or just see text?"
  ask_choice MENTION_C "What did they report?" \
    "Real @mention with a notification" \
    "Plain text, no notification" \
    "Nothing arrived"
  record "### 4. Mention test C — second person"
  record_kv "Observed result" "$MENTION_C"
  record "Response:"
  record_fenced json "$RESP_C"
else
  SKIPPED+=("Mention test C (second person) — re-run this wizard when a colleague is available")
  record "### 4. Mention test C — second person"
  record_kv "Observed result" "SKIPPED — no second person available"
  warn "Skipped. Ticket 06 is not fully resolved until this is done."
fi
record ""
pause "Press Enter to continue."

# ── Stage 5 — rate limit ──────────────────────────────────────────────────
stage "Rate limit — 20 messages/minute per webhook"
say "The Digest and reminder batching in ticket 08 are designed around this number."
say "Docs say 20/min per webhook; nobody has confirmed what exceeding it does."
printf '\n'
warn "This sends ~25 messages in a burst. Only do it in the throwaway test group."
printf '\n'
if confirm "Run the burst now?"; then
  RATE_FIRST_FAIL=""; RATE_FAIL_BODY=""
  i=1
  while [ "$i" -le 25 ]; do
    _p=$(jq -nc --arg n "$i" '{msgtype:"text",text:{content:("[06] rate probe " + $n + "/25")}}')
    _r=$(robot_send "$_p")
    _code=$(printf '%s' "$_r" | jq -r '.errcode // "unparseable"' 2>/dev/null || echo unparseable)
    printf '  %s/25 → errcode %s\n' "$i" "$_code"
    if [[ "$_code" != "0" && -z "$RATE_FIRST_FAIL" ]]; then
      RATE_FIRST_FAIL="$i"; RATE_FAIL_BODY="$_r"
    fi
    i=$((i + 1))
  done
  printf '\n'
  record "### 5. Rate limit"
  if [[ -n "$RATE_FIRST_FAIL" ]]; then
    say "First non-zero errcode at message $RATE_FIRST_FAIL of 25."
    record_kv "First rejection" "message $RATE_FIRST_FAIL of 25"
    record "Rejection body:"
    record_fenced json "$RATE_FAIL_BODY"
  else
    say "All 25 accepted — the limit was not hit in a single burst."
    record_kv "First rejection" "none — all 25 accepted in one burst"
  fi
  step "Check the group: did all the accepted messages actually arrive?"
  ask_note RATE_DELIVERED "How many of the 25 landed in the group?"
  record_kv "Actually delivered" "$RATE_DELIVERED of 25"
else
  SKIPPED+=("Rate-limit burst probe")
  record "### 5. Rate limit"
  record_kv "Observed" "SKIPPED — docs claim 20/min, unverified"
fi
record ""
say "The robot half of ticket 06 is now done. Everything below may hit a wall —"
say "that is fine. A known blocker is a finding, not a failure."
pause "Press Enter to move to the admin console."

# ── Stage 6 — org verification state ──────────────────────────────────────
stage "Org verification state — 未验证 / 已验证 / 已认证"
say "Configuring a 可信域名 at all requires 已验证 or 已认证. Without a trusted"
say "domain there is no WeCom login flow. This is the gate on ticket 07."
open_url "https://work.weixin.qq.com/wework_admin/frame"
printf '\n'
step "Sidebar: My Company → Company Profile  (我的企业 → 企业信息)."
step "Look for the verification badge / Company Verification row (企业认证)."
printf '\n'
warn "Taihue's console renders in ENGLISH. English collapses 已验证 and 已认证 —"
warn "two states with different costs — into one word, 'Verified'. If it reads"
warn "Verified, switch the console to 简体中文 before answering; 未验证/Unverified"
warn "is unambiguous either way."
printf '\n'
ask_choice ORG_STATE "What is Taihue's state?" \
  "已认证 (verified, paid certification)" \
  "已验证 (verified)" \
  "未验证 (unverified)" \
  "Can't tell — the console doesn't say plainly"
ask_block ORG_STATE_TEXT "Transcribe any verification text the console shows (verbatim):"
record "### 6. Org verification state"
record_kv "State" "$ORG_STATE"
record_label "Verbatim console text:"
record_fenced "" "$ORG_STATE_TEXT"
case "$ORG_STATE" in
  未验证*) warn "Unverified. 可信域名 configuration is expected to be blocked outright."
           warn "认证 costs RMB 300+ per app plus a member-size fee, and has third-party"
           warn "review lead time. Stage 8 will confirm whether it blocks." ;;
esac
pause "Press Enter to continue."

# ── Stage 7 — the self-built app ──────────────────────────────────────────
stage "Self-built app — create it, capture the credentials"
say "Credentials go to .env at the repo root only. Never into a ticket."
open_url "https://work.weixin.qq.com/wework_admin/frame#apps"
printf '\n'
step "Sidebar: App Management → Custom / Self-built → Create an App"
step "  (应用管理 → 应用 → 自建 → 创建应用)."
note "It demands an app logo. A ready-made 750x750 PNG is in this directory:"
note "  .scratch/tender-tracker-mvp/app-logo.png"
step "Give it a name (e.g. Tender Tracker), a logo, and visible members."
printf '\n'
step "Corp ID: My Company → Company Profile → CorpID (我的企业 → 企业信息 → 企业ID)."
note "It is the LAST row on that page — scroll to the bottom. Org-wide, not per-app."
ask WECOM_CORP_ID "Paste the Corp ID (企业ID):"
step "Agent ID: on the app's own page, labelled AgentId."
ask WECOM_AGENT_ID "Paste the Agent ID:"
step "Secret: on the same page, click View (查看) next to Secret. WeCom sends it to you"
step "  via the 企业微信 app rather than showing it inline — check your messages."
ask_secret WECOM_SECRET "Paste the app Secret (hidden):"
write_env WECOM_CORP_ID "$WECOM_CORP_ID"
write_env WECOM_AGENT_ID "$WECOM_AGENT_ID"
write_env WECOM_SECRET "$WECOM_SECRET"
record "### 7. Self-built app"
record_kv "App created" "yes"
record_kv "Credential storage (decision)" "\`.env\` at repo root — gitignored, never committed. Not a secret manager: solo developer, greenfield, no CI yet."
record_kv "Keys" "\`WECOM_CORP_ID\`, \`WECOM_AGENT_ID\`, \`WECOM_SECRET\`"
record ""
pause "Press Enter for the decisive test."

# ── Stage 8 — the trusted domain attempt ──────────────────────────────────
stage "可信域名 — the test that decides ticket 07"
say "Neither research ticket could settle this from documentation: WeCom publishes"
say "no policy covering orgs registered under a non-mainland entity. You are the"
say "admin. Five minutes here beats another week of reading."
printf '\n'
step "On the app's page: Developer Interface → Web Authorization and JS-SDK"
step "  → Trusted Domain  (开发者接口 → 网页授权及JS-SDK → 设置可信域名)."
warn "There are TWO fields. Use the OAuth one — it gates redirect_uri. The JS-SDK"
warn "field is for in-client JS APIs and has nothing to do with login."
warn "Use a domain Taihue CONTROLS. A domain that does not resolve fails the"
warn "ownership (归属) check and never reaches the 备案/ICP question — which is"
warn "the only thing this stage exists to answer."
step "Try to add a domain. Use one Taihue actually owns, if any; otherwise use"
step "  the domain you intend to ship on."
step "SCREENSHOT whatever happens — success, error, or a greyed-out control."
note "WeCom's own rules page: https://open.work.weixin.qq.com/help2/pc/21316"
open_url "https://open.work.weixin.qq.com/help2/pc/21316"
printf '\n'
ask_note TRUSTED_DOMAIN "Which domain did you try?"
ask_choice DOMAIN_OUTCOME "What happened?" \
  "Blocked on org verification (需已验证/认证企业才可操作)" \
  "Rejected on 备案/主体 grounds (域名主体校验未通过 or an MIIT filing demand)" \
  "ACCEPTED — the domain was saved" \
  "Something else / the control was not there at all"
ask_block DOMAIN_TEXT "Transcribe the exact message the console gave (verbatim, Chinese as shown):"
say "Save your screenshot to: $SHOTS_DIR/"
ask_note DOMAIN_SHOT "Screenshot filename (e.g. 06-trusted-domain.png), or blank:"
record "### 8. 可信域名 attempt — DECISIVE FOR TICKET 07"
record_kv "Domain tried" "\`$TRUSTED_DOMAIN\`"
record_kv "Outcome" "$DOMAIN_OUTCOME"
[[ -n "$DOMAIN_SHOT" ]] && record_kv "Screenshot" "\`$DOMAIN_SHOT\`"
record_label "Verbatim console text:"
record_fenced "" "$DOMAIN_TEXT"
printf '\n'
case "$DOMAIN_OUTCOME" in
  Blocked*)  warn "Verification is the prerequisite. Establish 已验证/认证 first, then re-run."
             record "**Reading:** verification is a hard prerequisite; retry after 已验证/认证." ;;
  Rejected*) warn "This confirms the catch-22 from ticket 03: ICP filing needs a mainland"
             warn "entity AND mainland-hosted servers, so an ICP-filed 可信域名 and Vercel are"
             warn "mutually exclusive. WeCom web-OAuth login is DEAD for v1. Ticket 07 should"
             warn "choose email/password and key identity on wecom_userid later."
             record "**Reading:** confirms the ICP catch-22 (research/03-hosting.md §3.4). WeCom web-OAuth login is dead for v1; ticket 07 should take email/password." ;;
  ACCEPTED*) warn "This contradicts every document we have. Overseas-entity orgs may be"
             warn "treated differently than the docs imply. Record it carefully — it REOPENS"
             warn "WeCom login as genuinely viable and ticket 07 must weigh it."
             record "**Reading:** contradicts research/02 and /03. No documentation states this. Reopens WeCom login as viable — ticket 07 must reconsider." ;;
  *)         record "**Reading:** inconclusive — see verbatim text above." ;;
esac
record ""
printf '\n'
step "While you are here, note the form's constraints: how many OAuth2 callback"
step "  domains does it allow? Does it demand a WW_verify_*.txt file at the root?"
ask_block DOMAIN_FORM "Anything the form demanded or limited (blank + . to skip):"
record_label "Form constraints observed:"
record_fenced "" "$DOMAIN_FORM"
pause "Press Enter to continue."

# ── Stage 9 — trusted IP ──────────────────────────────────────────────────
stage "企业可信IP (Trusted Enterprise IP) — is the whitelist enforced?"
say "Ticket 03 found the policy: apps created after 2022-06-20 20:00 must whitelist"
say "calling IPs. This decides whether Vercel serverless can host WeCom-facing code."
printf '\n'
warn "gettoken alone is NOT a valid test — it is EXEMPT from the whitelist and"
warn "returns errcode 0 even when every business API is blocked. Observed"
warn "2026-08-12. Ticket 06's own step 3 proposed that misleading test."
say "So we get a token, then call real business endpoints with it."
printf '\n'
warn "Do NOT add this machine's IP to 企业可信IP first — that destroys the test."
printf '\n'
if confirm "Is 企业可信IP (Trusted Enterprise IP) still empty for this app?"; then
  say "Getting a token…"
  TOKEN_RESP=$(curl -sS --get \
    --data-urlencode "corpid=$WECOM_CORP_ID" \
    --data-urlencode "corpsecret=$WECOM_SECRET" \
    "$QYAPI/gettoken" 2>&1 || true)
  TOKEN_CODE=$(printf '%s' "$TOKEN_RESP" | jq -r '.errcode // "unparseable"' 2>/dev/null || echo unparseable)
  TOKEN=$(printf '%s' "$TOKEN_RESP" | jq -r '.access_token // empty' 2>/dev/null || true)
  note "(access_token deliberately not printed or recorded)"
  record "### 9. 企业可信IP / business-API access"
  record_kv "Called from" "an ordinary machine, IP NOT in 企业可信IP"
  record ""
  record "| Endpoint | errcode |"
  record "|---|---|"
  record "| \`/cgi-bin/gettoken\` | \`$TOKEN_CODE\` |"
  printf '\n'
  say "gettoken → errcode $TOKEN_CODE"
  BIZ_CODE="no-token"
  if [[ -n "$TOKEN" ]]; then
    for _ep in department/list user/simplelist; do
      _br=$(curl -sS --get --data-urlencode "access_token=$TOKEN" \
              --data-urlencode "department_id=1" "$QYAPI/$_ep" 2>&1 || true)
      _bc=$(printf '%s' "$_br" | jq -r '.errcode // "unparseable"' 2>/dev/null || echo unparseable)
      say "$_ep → errcode $_bc"
      record "| \`/cgi-bin/$_ep\` | \`$_bc\` |"
      [[ "$BIZ_CODE" == "no-token" ]] && BIZ_CODE="$_bc"
    done
  fi
  record ""
  printf '\n'
  case "$BIZ_CODE" in
    60020) warn "Confirmed: every WeCom business API needs a stable, enterprise-attributable"
           warn "egress IP. This DISQUALIFIES Vercel serverless for WeCom-facing code."
           warn "The proportionate fix is a ~\$5/mo fixed-IP VM as a thin API proxy —"
           warn "NOT Vercel Static IPs at \$100/mo. The group robot webhook is EXEMPT,"
           warn "so 'robot only' removes this cost entirely — a real scope cut for 11."
           record "**Reading:** whitelist enforced. \`gettoken\` is exempt and misleadingly returns 0; business APIs return 60020. Vercel serverless is disqualified for WeCom-facing code — use a ~\$5/mo fixed-IP VM as a thin proxy, not Vercel Static IPs (\$100/mo). The robot webhook is exempt." ;;
    0)     warn "Business APIs succeeded without whitelisting. That contradicts the"
           warn "post-2022-06-20 policy — record carefully, it reopens Vercel as viable."
           record "**Reading:** business APIs succeeded WITHOUT an IP whitelist — contradicts the post-2022-06-20 policy. Reopens Vercel serverless as viable for WeCom-facing code." ;;
    *)     record "**Reading:** unexpected errcode \`$BIZ_CODE\` — investigate before ticket 12 relies on it." ;;
  esac
else
  SKIPPED+=("gettoken 60020 test — 企业可信IP was already populated")
  record "### 9. 企业可信IP / gettoken"
  record_kv "Observed" "SKIPPED — 企业可信IP already populated, test invalid"
fi
record ""
pause "Press Enter for the last stage."

# ── Stage 10 — restrictions sweep and close out ───────────────────────────
stage "Restrictions sweep — and anything contradicting buildspec_1"
say "Last thing the ticket asks for: whatever the console surfaced along the way."
printf '\n'
step "Org-verification prompts, member limits, admin-permission gates, paywalls,"
step "  anything that nagged you or refused you."
ask_block RESTRICTIONS "Restrictions the console surfaced (blank + . to skip):"
printf '\n'
step "And the question ticket 12 will ask: did anything here contradict buildspec_1?"
ask_block CONTRADICTIONS "Contradictions with buildspec_1 (blank + . to skip):"
record "### 10. Restrictions and contradictions"
record_label "Restrictions surfaced:"
record_fenced "" "$RESTRICTIONS"
record_label "Contradicts \`buildspec_1\`:"
record_fenced "" "$CONTRADICTIONS"
record ""
record "---"
record ""
record "**Handoff.** Ticket 07 reads §6 and §8 (whether WeCom login is available at all)"
record "and §9 (whether Vercel can host WeCom-facing code). Ticket 08 reads §2–§5 —"
record "if mention test A failed, reopen 08."
record ""

finish
printf '  %sFindings:%s %s\n' "$BOLD" "$RESET" "$FINDINGS"
printf '  %sNext:%s record the resolution in issues/06-register-wecom-app-and-robot.md,\n' "$BOLD" "$RESET"
printf '        then update map.md. Tickets 07 and 12 read this.\n\n'
