#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES — the hand-checks that need a real phone, now covering the redesign.
#
# Unlike most wizards, this one captures *observations*, not credentials. The
# answers persist to a scratch env file only so that a run stopped halfway can
# be resumed — Enter keeps what you already answered. The output is a Markdown
# comment for the issue, assembled in the last stage.
#
# Written for #48 and rewritten for #68. Two things changed under it:
#
#   1. **Reminders now carry a link** (#59, `src/lib/app-links.ts`). The
#      original run could not perform the tap this whole procedure is about
#      and had to hand-post a bare URL instead. It now lands on the Tender.
#   2. **The redesign changed every screen** (#76). New group headings, a
#      per-row lamp and deadline sentence, the "waiting on you" band, a bar
#      that states where you are, and a declared CJK stack that is drawn by
#      the handset — so what the type looks like is now a fact about the
#      phone in your hand and cannot be checked anywhere else.
#
# That second one is why stage 7 exists. Roughly 25 new `zh-Hans` strings
# shipped drafted from the design canvas, and review already caught one
# saying the wrong thing. No test can tell you a sentence is wrong in the
# right language.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

ISSUE=68
REPO="Mikepeerawit-com/tender-tracker"
APP="${APP:-https://tenders.mikepeerawit.com}"

# Answers live here, not in .env — nothing this wizard collects is configuration.
ENV_FILE=".wizard/68-phone-checks.env"
mkdir -p "$(dirname "$ENV_FILE")"

# verdict KEY "Question" — a pass/fail/blocked answer that persists, so a
# resumed run offers it back. `confirm` is y/N only and remembers nothing,
# which is the wrong shape for a record somebody else will read.
verdict() {
  local key="$1" prompt="$2" tries=0
  while true; do
    ask "$key" "$prompt [pass/fail/blocked]:"
    case "${!key}" in
      pass|fail|blocked) break ;;
      *) warn "answer pass, fail, or blocked — 'blocked' means you could not run it at all." ;;
    esac
    # `ask` swallows a failed read, so end-of-input looks the same as an empty
    # answer and this loop would spin forever on it — which is what a piped or
    # backgrounded run gives you. Three refusals is a person mistyping; more
    # than that is nobody there.
    tries=$((tries + 1))
    if (( tries >= 3 )); then
      printf '\n'
      warn "no readable answer after $tries tries — stopping."
      note "answers so far are saved to $ENV_FILE; re-run to resume."
      exit 1
    fi
  done
  write_env "$key" "${!key}"
}

# observe KEY "Prompt" — a single-line note that persists. Single-line because
# the record is one KEY=VALUE per line; put long findings in the issue itself.
observe() {
  local key="$1" prompt="$2"
  ask "$key" "$prompt"
  write_env "$key" "${!key}"
}

banner "Tender Tracker — the phone checks after the redesign (#$ISSUE)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Preflight — what you are about to check, and on what"

say "These checks gate the redesign. They are hand-checks by decision, not by"
say "omission: density is a judgement, the WeCom webview cannot be driven from"
say "CI, and whether a Chinese sentence is *right* is not a thing a test can"
say "answer. A green tick nobody earned is what #$ISSUE exists to refuse."
printf '\n'
say "Confirming production is up and serving the build you mean to check:"

if curl -fsS --max-time 15 "$APP/api/health" 2>/dev/null | head -c 500; then
  printf '\n\n'
  say "That is the live health body. Two things to read in it:"
  step "\"status\": it must say ok. If it does not, stop and fix that first."
  step "\"appOrigin\": it must report an origin, not a fault."
  note "  A deployment with no APP_ORIGIN sends reminders that carry no link —"
  note "  and the link is what stage 2 taps. no-app-origin is its own health"
  note "  status for exactly this reason (#59, ADR-0016)."
else
  warn "could not reach $APP/api/health — check the deployment before going further."
fi

printf '\n'
note "Everything below is judged on a real handset. A narrowed desktop window"
note "will not surface a tap target, and it will not show you the CJK face the"
note "phone actually draws — which is the whole reason these are here."
printf '\n'
observe DEVICE_IOS "iOS device + iOS version (or 'none'):"
observe DEVICE_ANDROID "Android device + Android version (or 'none'):"
observe WECOM_VERSION "WeCom app version on the phone you will use:"
pause "Ready."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Get a reminder, with its link, into the WeCom group"

say "This is the tap the whole procedure is about, and the original run could"
say "not perform it: at the time no group message carried a URL. Since #59 a"
say "reminder ends with a link to the Tender, so the nag and the job are one"
say "tap apart — and that path is now checkable as written."
printf '\n'
say "Two ways to get one into the group. The first is safe; the second is the"
say "real thing and posts real Tenders to the real group chat."
printf '\n'

if confirm "Post a reminder-shaped message with a real link (no real Tender data)?"; then
  say "Paste the group robot webhook. It is not written to disk, and it is the"
  say "same credential the admin screen deliberately never echoes back."
  note "Find it in WeCom: group → ⋯ → Group Robot → your robot → Webhook URL."
  ask_secret ROBOT_WEBHOOK "Webhook URL (Enter to skip and paste the link by hand):"
  observe TENDER_ID "A Tender id to link to (from a /tenders/<id> URL in your browser):"

  LINK="$APP/tenders/${TENDER_ID:-}"

  if [[ -n "${ROBOT_WEBHOOK:-}" && -n "${TENDER_ID:-}" ]]; then
    say "Posting..."
    if curl -fsS --max-time 20 -H 'Content-Type: application/json' \
        -d "{\"msgtype\":\"text\",\"text\":{\"content\":\"【招标跟踪】发布前检查·请在手机上点击以下链接。\\n$LINK\"}}" \
        "$ROBOT_WEBHOOK" | head -c 200; then
      printf '\n'
      say "errcode 0 means WeCom accepted it — look at the group to see it arrive."
    else
      warn "the post failed; paste $LINK into the group by hand instead."
    fi
  else
    say "Paste this into the WeCom group yourself, from any WeCom client:"
    say "  $LINK"
    note "A bare URL in a group text message is tappable, which is all this needs."
  fi
  printf '\n'
  note "This message is hand-posted for the check and is deliberately not part of"
  note "the app's message catalogue. It names no Tender, no price, no supplier —"
  note "only an id, which is all ADR-0012 lets a link carry anyway."
  observe NOTE_ENTRY "How the link got into the group (one line):"
else
  warn "The real path posts real reminders about real Tenders to the real group."
  say "It runs the daily cron early. Everyone in the group sees whatever is due,"
  say "and ADR-0005's suppression rules mean somebody may get the same nag twice"
  say "today. Do this when you want the genuine article and the group is warned."
  printf '\n'
  say "  curl -H \"Authorization: Bearer \$CRON_SECRET\" $APP/api/cron/daily"
  printf '\n'
  note "CRON_SECRET is in the Vercel project's environment. A deployment without"
  note "one refuses every call rather than defaulting to open, so an empty value"
  note "will simply be turned away."
  observe NOTE_ENTRY "How the link got into the group (one line):"
fi
pause "A tappable link is in the group?"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Check 2a — the WeCom in-app webview: entry, banner, login, arrival"

say "On the phone, in WeCom, tap the link in the group. Do not open it in Safari"
say "or Chrome — the point is the webview a reminder actually lands in."
printf '\n'
step "Does the page open at all?"
step "Is there a WeCom security banner (防欺诈盗号 or similar) above the form?"
note "  A permanent banner is expected and cosmetic — this org cannot remove it."
note "  What matters is that it warns rather than blocks. Screenshot it either way."
step "Log in with email and password."
step "Read every screen you pass for the words \"open in your browser\"."
note "  That advice must never appear: there is no way out of this webview."
printf '\n'
say "Then judge the arrival, which is what the redesign was for:"
step "After login, do you land on the Tender the link named — not the list?"
step "Does the app bar say where you are: a back control, the reference, the"
note "  client name? And does it stay on ONE row at this width?"
step "If you owe anything on this Tender, is there a \"等你处理\" band at the top"
note "  naming the items, each one a link straight to its sourcing screen?"
note "  If you owe nothing it is correctly absent — that emptiness is the point."
printf '\n'
verdict CHECK_WEBVIEW_LOGIN "Login works in the webview, no blocking banner, no browser advice"
verdict CHECK_ARRIVAL "The link lands on the Tender, the bar says where you are, the band is right"
observe NOTE_BANNER "Banner: absent, or its exact wording + does it block? (one line):"
observe NOTE_ARRIVAL "Anything wrong about the arrival (one line):"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Check 2b — the WeCom webview: camera, and compress-and-upload"

say "Still inside WeCom, still on the phone. Go to a Tender Item and add a quote:"
say "  $APP/tenders → a Tender → an Item → Add quote"
printf '\n'
say "The screen was rebuilt in #75, so read it before you touch the camera:"
step "Does it show what the client asked for — 客户的需求 — above the price"
note "  field, with the Reference Images, so you can check what you are pricing?"
step "Is \"找不到供应商\" offered on this same screen, not behind another tap?"
printf '\n'
step "Tap the Quote Photo input."
step "What happens — camera, gallery, a chooser sheet, or nothing at all?"
note "  accept=\"image/*\" capture is a hint, not a guarantee. If a sheet appears,"
note "  note its options; if nothing happens, the fallback is what has to carry it."
step "Take a photo and come back. Does the app return without crashing?"
step "Let the upload finish. Does it complete, and is the stored image a real"
note "  picture rather than a blank or black rectangle?"
note "  WebKit silently produces a blank bitmap when a canvas exceeds its area"
note "  limit, and a 48 MP photo exceeds it — so look at the result, don't assume."
printf '\n'
verdict CHECK_WEBVIEW_CAMERA "Camera opens, photo returns, compress-and-upload completes"
observe NOTE_PICKER "What the photo input actually opened (one line):"
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Check 1 — density, 44px tap targets, and the lamp, at 390px"

say "On the phone, in any browser. Walk every screen and judge it."
printf '\n'
step "1  Login              $APP/login"
step "2  Worklist           $APP/tenders"
step "3  Tender detail      a Tender from that list"
step "4  Add / edit tender  $APP/tenders/new  (and an existing Tender's Edit)"
step "5  Add quote          a Tender → an Item → Add quote"
step "6  Edit quote         an existing Quote → Edit"
step "7  Working sheet      a Tender with several Items and competing Quotes"
printf '\n'
say "The densest case is the working sheet — an Item with eight competing"
say "Quotes, where the nine columns become one stacked card each below 768px."
printf '\n'
say "New since the redesign, and only checkable here:"
step "The app bar stays ONE row on every screen at this width."
step "Every tap target is comfortably thumb-sized — the 44px floor."
step "The indicator lamp reads without colour. Squint, or turn the phone to"
note "  greyscale in accessibility settings: a calm row and an urgent row must"
note "  still be tellable apart, because #71 requires shape and a sentence to"
note "  carry the meaning and not the hue alone."
step "Nothing scrolls sideways, anywhere, on any of the seven."
printf '\n'
note "CI already holds the failure bar that is arithmetic: no horizontal overflow"
note "at 390x844 and the bar staying one row, asserted in screens.layout.test.tsx."
note "It deliberately does not assert the 44px floor, because a green gate there"
note "is the false confidence this check exists to prevent."
printf '\n'
verdict CHECK_390 "Density is usable, tap targets are 44px+, the lamp survives greyscale"
observe NOTE_390 "Anything cramped or hard to hit, and where (one line):"
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Check 3 — Android's camera, or the gap recorded"

say "If no Android handset is available, answer 'blocked' — recording the gap is"
say "an acceptable outcome here, and the honest one."
printf '\n'
step "On Android, open the app and go to Add quote."
step "Tap the photo input. Does capture fire, or do you get the file picker?"
note "  Android WebView cancels file requests unless the host app opts in, and"
note "  WeCom's implementation is reported inconsistent. The file-picker fallback"
note "  is what actually carries this — confirm it is visible and it works."
step "Do it inside WeCom's webview too, if you can, not only Chrome."
printf '\n'
say "And while you are on a second handset, look at the type:"
step "Does the Chinese render in a real CJK face rather than a fallback?"
note "  ADR-0019 declares the stack and lets the device draw it — PingFang SC,"
note "  Hiragino Sans GB, Source Han Sans SC, Noto Sans SC, Microsoft YaHei —"
note "  with no webfont, because a CJK face cannot be subset and would be"
note "  megabytes over a phone network. So the face differs by handset BY"
note "  DESIGN, and two phones disagreeing is not a bug. What would be a bug is"
note "  Chinese rendering in something that is obviously not a CJK face at all."
printf '\n'
verdict CHECK_ANDROID "Android camera checked (or 'blocked' if no device was available)"
observe NOTE_ANDROID "What Android did, or why it could not be checked (one line):"
observe NOTE_FONT "How the Chinese rendered on each handset (one line):"
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Check 5 — the redesign's Chinese, read by somebody fluent"

warn "This one needs a fluent reader. If that is not you, stop and hand it over."
printf '\n'
say "The redesign shipped roughly 25 new zh-Hans strings, drafted from the"
say "design canvas in the voice of the existing message files and never read by"
say "a native eye. #$ISSUE says so itself. Review already caught one saying the"
say "wrong thing: 尚无报价 meant *no quote yet*, which is the count #71"
say "explicitly forbids — it nags an Assignee who already rang round and"
say "reported back. That one is fixed. The rest have had no such reading."
printf '\n'
say "Switch to 简体中文 and judge these IN PLACE, on the screen, not as a list."
say "A sentence can be correct Chinese and still be the wrong sentence there —"
say "which is exactly how 尚无报价 got through."
printf '\n'
say "On the worklist, the four group headings and their hints:"
step "尚未开始 · 已录入，还没有人开始联系供应商。"
step "询价中 · 负责人正在收集价格。可能仍有明细无人认领。"
step "报价已齐 · 每项明细都已有价格，等待有人选定报价并提交投标。"
step "已提交 · 投标已交到客户手上。这不是出了问题——在这里跟进他们。"
note "  已提交's hint has to read as reassurance, not as a fault."
printf '\n'
say "On the rows, the deadline sentences — find one of each if you can:"
step "报价今天截止 / 报价明天截止 / 报价 {date} 截止 / 报价原定 {date} 截止"
step "今天须提交客户 / 明天须提交客户 / {date} 须提交客户 / 原定 {date} 提交客户"
step "截止日期已过 {days} 天"
step "{total} 项中有 {count} 项尚未询价"
step "{date} 起等待客户答复"
note "  The passed readings (原定) must read as \"was due\", not as \"is due\"."
note "  尚未询价 must mean neither a quote NOR a no-supplier-found record —"
note "  not merely \"has no quote\"."
printf '\n'
say "On the Tender detail, the band:"
step "等你处理 · 以下明细你既没有录入报价，也没有记为找不到供应商。"
note "  It has to read as a personal to-do, not as a team status report."
printf '\n'
say "On the add-quote and working sheets:"
step "客户的需求 — the heading over what the client asked for."
step "未确认 — an unconfirmed Landed Cost. Must read as provisional, not wrong."
step "菜单 · 返回 — the bar's menu and back controls."
printf '\n'
verdict CHECK_CHINESE "A fluent reader has read every new string in place and they are right"
observe WHO_READ "Who read it (name), or 'nobody yet':"
observe NOTE_CHINESE "Any string that reads wrong, and where (one line):"
pause

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Check 4 — every screen, read through in both locales"

say "The switcher is in the app header, and on the login screen itself."
printf '\n'
step "Read all seven screens in English."
step "Switch to 简体中文 and read all seven again."
step "Confirm your choice survives a reload — it persists to users.locale, not"
note "  only to the cookie, so a different device should see it too."
printf '\n'
say "This is the layout half, where stage 7 was the wording half:"
step "Nothing overflows or wraps badly in either locale."
note "  A Han glyph is roughly twice the width of a Latin letter, so a shorter"
note "  Chinese string is not automatically a narrower control (#$ISSUE)."
step "No raw message key is ever on screen — a key would look like tenders.foo."
printf '\n'
note "The sweep in #47 already holds everything a machine can decide: every"
note "literal t(\"…\") resolves in both locales, every union the UI builds a key"
note "from is walked, and no placeholder, alt or aria-label is hardcoded. A typo"
note "fails the suite. So you are not hunting raw keys — you are judging whether"
note "the layout holds, which is what that sweep structurally cannot do."
printf '\n'
note "User-entered content stays in whatever language it was typed in. A Tender"
note "title in Thai reading as Thai under zh-Hans is correct, not a miss."
printf '\n'
verdict CHECK_LOCALES "Both locales hold their layout across every screen"
observe NOTE_LOCALES "Anything that broke, and where (one line):"
pause

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Record the result on #$ISSUE"

# box VERDICT — a markdown checkbox. Returns the brackets whole rather than the
# character inside them: `$(…)` strips trailing whitespace, so a function that
# printed a bare space for "unticked" would yield `- []`, which renders as text.
box() { [[ "$1" == "pass" ]] && printf '[x]' || printf '[ ]'; }

# line "VERDICT" "Label" "Note" — one checklist row. The note rides on the same
# line: an indented continuation four spaces past the list content becomes a
# code block on GitHub, which is not what a one-line finding should look like.
line() {
  local note="$3"
  [[ -z "$note" ]] && note="no notes"
  printf -- '- %s **%s** — %s. %s\n' "$(box "$1")" "$2" "$1" "$note"
}

COMMENT=$(mktemp)

{
  printf '## Hand-checks run on a real phone, after the redesign\n\n'
  printf 'Run with `scripts/prelaunch-phone-checks.sh` on %s.\n\n' "$(date '+%Y-%m-%d')"
  printf '| | Device |\n|---|---|\n'
  printf '| iOS | %s |\n' "${DEVICE_IOS:-—}"
  printf '| Android | %s |\n' "${DEVICE_ANDROID:-—}"
  printf '| WeCom | %s |\n\n' "${WECOM_VERSION:-—}"

  line "$CHECK_390"            "390px: density, 44px, the lamp in greyscale" "${NOTE_390:-}"
  line "$CHECK_WEBVIEW_LOGIN"  "WeCom webview — entry and login"            "${NOTE_BANNER:-}"
  line "$CHECK_ARRIVAL"        "The reminder link's arrival"                "${NOTE_ARRIVAL:-}"
  line "$CHECK_WEBVIEW_CAMERA" "WeCom webview — camera and upload"          "${NOTE_PICKER:-}"
  line "$CHECK_ANDROID"        "Android camera"                             "${NOTE_ANDROID:-}"
  line "$CHECK_CHINESE"        "The new Chinese, read by a fluent reader"    "${NOTE_CHINESE:-}"
  line "$CHECK_LOCALES"        "Both locales, every screen"                 "${NOTE_LOCALES:-}"
  printf '\n'

  printf '### The Chinese\n\n'
  printf 'Read by: **%s**.\n\n' "${WHO_READ:-nobody yet}"
  printf 'This is the half of #%s that no test reaches. Roughly 25 strings shipped\n' "$ISSUE"
  printf 'drafted from the design canvas — the group headings and hints, the row deadline\n'
  printf 'sentences, the outstanding-for-you band, `客户的需求` and `未确认` — and they were\n'
  printf 'judged in place on the screen rather than as a list, because a sentence can be\n'
  printf 'correct Chinese and still be the wrong sentence where it sits.\n\n'
  printf 'Type rendering: %s\n\n' "${NOTE_FONT:-—}"
  printf 'The CJK face differs by handset by design (ADR-0019): the stack is declared and\n'
  printf 'drawn by the device, with no webfont, because a CJK face cannot be subset and\n'
  printf 'would be megabytes over a phone network inside the webview. Two phones\n'
  printf 'disagreeing about the face is not a defect.\n\n'

  printf '### On the entry path\n\n'
  printf 'The original run of this procedure (#48) could not perform the tap it is about:\n'
  printf 'no group message carried a URL, so the webview was reached by hand-posting a\n'
  printf 'bare address. Since #59 a reminder ends with a link to the Tender, and\n'
  printf '`/api/health` reports a missing `APP_ORIGIN` as its own status so a deployment\n'
  printf 'cannot reach production with linkless reminders unnoticed (ADR-0016).\n\n'
  printf 'How the link got into the group this run: %s\n' "${NOTE_ENTRY:-—}"
} > "$COMMENT"

_clear
printf '\n%s%s▸ Stage %s/%s · The comment%s\n\n' "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$RESET"
cat "$COMMENT"
printf '\n'

if confirm "Post this to #$ISSUE?"; then
  if gh issue comment "$ISSUE" --repo "$REPO" --body-file "$COMMENT"; then
    say "Posted."
    if [[ "$CHECK_390" == "pass" && "$CHECK_WEBVIEW_LOGIN" == "pass" \
       && "$CHECK_ARRIVAL" == "pass" && "$CHECK_WEBVIEW_CAMERA" == "pass" \
       && "$CHECK_CHINESE" == "pass" && "$CHECK_LOCALES" == "pass" ]]; then
      note "Every check but the Android gap passed — #$ISSUE is closable."
    else
      warn "Something did not pass. Leave #$ISSUE open until it does."
    fi
  else
    SKIPPED+=("post it: gh issue comment $ISSUE --repo $REPO --body-file $COMMENT")
  fi
else
  SKIPPED+=("post the comment yourself — it is saved at $COMMENT")
fi

finish
note "answers saved to $ENV_FILE — re-run to resume, Enter keeps each one"
